targets:
  $default:
    builders:
      objectbox_generator:generator:
        options:
          output_dir: core/services/objectbox
    sources:
      - $package$
      - lib/**
      - test/**
      - web/**
      - windows/**
      - macos/**
      - linux/**
      - android/**
      - ios/**
      - assets/**
      - '!example/**'
      - '!**/.plugin_symlinks/**'
